/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/retrieval/debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 执行检索调试 */
        post: operations["debug"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/{id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重新处理证据 */
        post: operations["reprocess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出事件 */
        get: operations["list"];
        put?: never;
        /** 创建事件并校验 EventIR */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出事件的调查运行 */
        get: operations["list_1"];
        put?: never;
        /** 发起新调查运行 */
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传证据文件 */
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}/evidence/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 添加文本证据 */
        post: operations["createText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}/evidence/bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 导入标准 Observation Bundle */
        post: operations["importBundle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/observations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 人工复核观察 */
        patch: operations["verify"];
        trace?: never;
    };
    "/api/v1/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取本地实例能力 */
        get: operations["runtime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/retrieval/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取检索运行快照 */
        get: operations["run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取知识单元详情与使用记录 */
        get: operations["unit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/units/{id}/retrieval-usages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页读取知识单元检索使用记录 */
        get: operations["retrievalUsages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/units/{id}/citation-usages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页读取知识单元引用记录 */
        get: operations["citationUsages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出知识源 */
        get: operations["sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取知识源详情 */
        get: operations["source"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/sources/{id}/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页读取知识源的知识单元 */
        get: operations["units"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出知识文档 */
        get: operations["documents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取调查运行快照 */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{id}/next-evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取下一步取证建议 */
        get: operations["nextEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{id}/knowledge-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取调查知识上下文 */
        get: operations["knowledgeContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 比较调查运行快照 */
        get: operations["diff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出证据 */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取证据详情 */
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取事件详情 */
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取事件聚合视图 */
        get: operations["view"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取调查运行的因果关系图 */
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页读取事件审计记录 */
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}/audit/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出事件审计 JSONL */
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domain-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出领域包 */
        get: operations["list_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domain-packs/{key}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取领域包版本详情 */
        get: operations["get_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domain-packs/{key}/versions/{version}/event-types/{eventType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取领域包事件定义 */
        get: operations["getEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RetrievalRequest: {
            query: string;
            event_type: string;
            observed_predicates?: string[];
            intent?: string;
            domain_pack_key: string;
        };
        ApiEnvelopeRetrievalRunView: {
            data: components["schemas"]["RetrievalRunView"];
            meta: components["schemas"]["Meta"];
        };
        Meta: {
            request_id: string;
            schema_version?: string;
        };
        RetrievalHitView: {
            knowledge_unit_id: string;
            document_id: string;
            source_id: string;
            title: string;
            content: string;
            /** Format: int32 */
            keyword_rank?: number;
            /** Format: double */
            keyword_score?: number;
            /** Format: int32 */
            vector_rank?: number;
            /** Format: double */
            vector_score?: number;
            /** Format: int32 */
            fusion_rank: number;
            /** Format: double */
            fusion_score: number;
            /** Format: double */
            applicability_score: number;
            applicability_reason: string;
            expected_predicates: string[];
            selected: boolean;
            selection_reason: string;
            source_locator: unknown;
            source_version: string;
            content_hash: string;
        };
        RetrievalIntentView: {
            type: string;
            query: string;
            hits: components["schemas"]["RetrievalHitView"][];
        };
        RetrievalRunView: {
            id: string;
            investigation_run_id?: string;
            index_version: string;
            embedding_provider: string;
            embedding_model: string;
            embedding_model_digest: string;
            index_profile_fingerprint: string;
            status: string;
            query_plan: unknown;
            retrieval_config: unknown;
            intents: components["schemas"]["RetrievalIntentView"][];
            context_hash: string;
            /** Format: date-time */
            created_at: string;
        };
        ApiEnvelopeEvidenceDetail: {
            data: components["schemas"]["EvidenceDetail"];
            meta: components["schemas"]["Meta"];
        };
        EvidenceDetail: {
            evidence: components["schemas"]["EvidenceSummary"];
            content_text?: string;
            blob_key?: string;
            /** Format: date-time */
            captured_at?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            metadata: unknown;
            observations: components["schemas"]["ObservationView"][];
        };
        EvidenceSummary: {
            id: string;
            event_id: string;
            type: string;
            source: string;
            status: string;
            original_name?: string;
            content_type?: string;
            checksum_sha256?: string;
            /** Format: int32 */
            generation: number;
            /** Format: double */
            reliability: number;
            /** Format: int32 */
            observation_count: number;
            /** Format: date-time */
            created_at: string;
        };
        ObservationView: {
            id: string;
            predicate: string;
            value: unknown;
            description?: string;
            /** Format: double */
            model_confidence: number;
            verification_status: string;
            provenance: unknown;
            /** Format: int32 */
            generation: number;
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateEventRequest: {
            /**
             * @example {
             *       "schema_version": "eventir/0.1",
             *       "event": {
             *         "type": "equipment_fault",
             *         "title": "设备温度异常",
             *         "reference_code": "EVT-DEMO-001",
             *         "domain_pack": "equipment-fault-test/1.0.0"
             *       },
             *       "subjects": [
             *         {
             *           "type": "equipment_asset",
             *           "label": "pump-001",
             *           "attributes": {
             *             "asset_id": "pump-001"
             *           }
             *         }
             *       ]
             *     }
             */
            event_ir: unknown;
        };
        ApiEnvelopeObject: {
            data: Record<string, never>;
            meta: components["schemas"]["Meta"];
        };
        ApiEnvelopeInvestigationRunView: {
            data: components["schemas"]["InvestigationRunView"];
            meta: components["schemas"]["Meta"];
        };
        ContributionView: {
            rule_id: string;
            rule_version: string;
            predicate: string;
            relation: string;
            /** Format: double */
            rule_weight: number;
            evidence_id: string;
            observation_id: string;
            /** Format: double */
            source_reliability: number;
            /** Format: double */
            extraction_confidence: number;
            /** Format: double */
            relevance: number;
            /** Format: double */
            value: number;
            reason: string;
        };
        EvidenceSnapshotItemView: {
            id: string;
            type: string;
            source: string;
            status: string;
            original_name?: string;
            content_type?: string;
            checksum_sha256?: string;
            /** Format: int32 */
            generation: number;
            /** Format: double */
            reliability: number;
            /** Format: date-time */
            created_at: string;
            observations: components["schemas"]["ObservationSnapshotView"][];
        };
        EvidenceSnapshotView: {
            /** Format: int32 */
            schema_version: number;
            evidence_ids: string[];
            evidence: components["schemas"]["EvidenceSnapshotItemView"][];
        };
        ExpectedEvidenceView: {
            predicate: string;
            /** Format: double */
            weight: number;
            relation: string;
            required: boolean;
            origin: string;
            rule_id: string;
        };
        HypothesisResultView: {
            id: string;
            code: string;
            title: string;
            description: string;
            /** Format: int32 */
            score: number;
            band: string;
            /** Format: double */
            coverage: number;
            /** Format: double */
            positive: number;
            /** Format: double */
            negative: number;
            /** Format: double */
            missing_penalty: number;
            expected_evidence: components["schemas"]["ExpectedEvidenceView"][];
            contributions: components["schemas"]["ContributionView"][];
            citation_ids: string[];
            grounding_status: string;
            knowledge_limitations: string[];
        };
        InvestigationResultView: {
            support_index_disclaimer: string;
            pipeline: string;
            planner_version: string;
            /** Format: int64 */
            event_version: number;
            evidence_snapshot_hash: string;
            knowledge_index_version: string;
            retrieval_run_id: string;
            knowledge_context_hash: string;
            evidence_snapshot: components["schemas"]["EvidenceSnapshotView"];
            hypotheses: components["schemas"]["HypothesisResultView"][];
            next_evidence: components["schemas"]["NextEvidenceView"][];
        };
        InvestigationRunView: {
            id: string;
            event_id: string;
            /** Format: int32 */
            sequence_no: number;
            status: string;
            /** Format: int64 */
            event_version: number;
            /** Format: int32 */
            evidence_snapshot_schema_version: number;
            evidence_snapshot_hash: string;
            evidence_snapshot: components["schemas"]["EvidenceSnapshotView"];
            model_policy_version: string;
            rule_pack_version: string;
            domain_pack_key: string;
            domain_pack_version: string;
            domain_pack_fingerprint: string;
            knowledge_index_version: string;
            retrieval_run_id?: string;
            event_ir_snapshot: unknown;
            result?: components["schemas"]["InvestigationResultView"];
            stale: boolean;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            completed_at?: string;
            error_code?: string;
            error_message?: string;
            /** Format: date-time */
            created_at: string;
        };
        NextEvidenceView: {
            id: string;
            recommendation_id?: string;
            evidence_type: string;
            title: string;
            expected_predicate?: string;
            reason: string;
            discriminates: string[];
            estimated_impact: string;
            acquisition_cost: string;
            /** Format: double */
            priority_score: number;
            status: string;
            source: string;
            /** Format: date-time */
            created_at: string;
        };
        ObservationSnapshotView: {
            id: string;
            /** Format: int32 */
            generation: number;
            /** Format: int64 */
            version: number;
            predicate: string;
            value: Record<string, never>;
            description?: string;
            /** Format: double */
            model_confidence: number;
            verification_status: string;
            present: boolean;
        };
        TextEvidenceRequest: {
            text: string;
            /** Format: date-time */
            captured_at?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
        };
        ObservationBundleEvidenceItem: {
            external_id: string;
            source_type: string;
            /** Format: date-time */
            captured_at: string;
            observations: components["schemas"]["ObservationBundleObservation"][];
        };
        ObservationBundleObservation: {
            predicate: string;
            value: unknown;
            /** Format: double */
            confidence: number;
            description?: string;
            source_locator: {
                [key: string]: unknown;
            };
        };
        ObservationBundleRequest: {
            schema_version: string;
            domain_pack: string;
            event_type: string;
            target_version?: string;
            subject: components["schemas"]["ObservationBundleSubject"];
            evidence_items: components["schemas"]["ObservationBundleEvidenceItem"][];
        };
        ObservationBundleSubject: {
            type: string;
            label: string;
            attributes?: {
                [key: string]: unknown;
            };
        };
        ApiEnvelopeObservationBundleImportView: {
            data: components["schemas"]["ObservationBundleImportView"];
            meta: components["schemas"]["Meta"];
        };
        ObservationBundleImportView: {
            schema_version: string;
            bundle_hash: string;
            duplicate: boolean;
            evidence: components["schemas"]["EvidenceDetail"][];
        };
        ObservationVerificationRequest: {
            verification_status: string;
            description?: string;
        };
        ApiEnvelopeObservationView: {
            data: components["schemas"]["ObservationView"];
            meta: components["schemas"]["Meta"];
        };
        ApiEnvelopeRuntimeView: {
            data: components["schemas"]["RuntimeView"];
            meta: components["schemas"]["Meta"];
        };
        RuntimeView: {
            api_version: string;
            deployment_mode: string;
            instance_name: string;
            capabilities: {
                [key: string]: boolean;
            };
        };
        ApiEnvelopeUnitDetailView: {
            data: components["schemas"]["UnitDetailView"];
            meta: components["schemas"]["Meta"];
        };
        CitationUsageView: {
            citation_id: string;
            investigation_run_id: string;
            event_id: string;
            target_type: string;
            target_id: string;
            target_code?: string;
            target_title?: string;
            source_locator: unknown;
            source_version: string;
            content_hash: string;
            usage_reason: string;
            /** Format: date-time */
            created_at: string;
        };
        DocumentView: {
            id: string;
            knowledge_source_id: string;
            external_id?: string;
            title: string;
            content_type: string;
            checksum_sha256: string;
            language: string;
            parse_status: string;
            metadata: unknown;
            /** Format: int32 */
            unit_count: number;
            /** Format: date-time */
            created_at: string;
        };
        EmbeddingProvenanceView: {
            provider: string;
            model: string;
            /** Format: int32 */
            dimension: number;
            model_digest: string;
            query_instruction: string;
            index_profile_fingerprint: string;
            production_ready: boolean;
        };
        RetrievalUsageView: {
            retrieval_run_id: string;
            investigation_run_id?: string;
            query_intent: string;
            /** Format: int32 */
            keyword_rank?: number;
            /** Format: int32 */
            vector_rank?: number;
            /** Format: int32 */
            fusion_rank: number;
            /** Format: double */
            fusion_score: number;
            selected: boolean;
            selection_reason: string;
            index_version: string;
            embedding_model: string;
            /** Format: date-time */
            created_at: string;
        };
        SourceView: {
            id: string;
            domain_pack_key: string;
            name: string;
            source_type: string;
            version: string;
            license?: string;
            status: string;
            fixture_only: boolean;
            production_allowed: boolean;
            /** Format: int32 */
            document_count: number;
            /** Format: int32 */
            unit_count: number;
            embedding_provider?: string;
            embedding_model?: string;
            /** Format: int32 */
            embedding_dimension?: number;
            embedding_model_digest?: string;
            embedding_query_instruction?: string;
            index_profile_fingerprint?: string;
            /** Format: date-time */
            published_at?: string;
            /** Format: date-time */
            created_at: string;
        };
        UnitDetailView: {
            id: string;
            source: components["schemas"]["SourceView"];
            document: components["schemas"]["DocumentView"];
            domain_pack_key: string;
            topic?: string;
            title: string;
            content: string;
            applicability: unknown;
            expected_predicates: unknown;
            source_locator: unknown;
            source_version: string;
            content_hash: string;
            status: string;
            embedding_present: boolean;
            embedding_provenance?: components["schemas"]["EmbeddingProvenanceView"];
            citation_usages: components["schemas"]["CitationUsageView"][];
            /** Format: int64 */
            citation_usage_count: number;
            citation_usages_next_cursor?: string;
            retrieval_usages: components["schemas"]["RetrievalUsageView"][];
            /** Format: int64 */
            retrieval_usage_count: number;
            retrieval_usages_next_cursor?: string;
            /** Format: date-time */
            created_at: string;
        };
        ApiEnvelopeRetrievalUsagePageView: {
            data: components["schemas"]["RetrievalUsagePageView"];
            meta: components["schemas"]["Meta"];
        };
        RetrievalUsagePageView: {
            items: components["schemas"]["RetrievalUsageView"][];
            next_cursor?: string;
            /** Format: int32 */
            limit: number;
            /** Format: int64 */
            total: number;
        };
        ApiEnvelopeCitationUsagePageView: {
            data: components["schemas"]["CitationUsagePageView"];
            meta: components["schemas"]["Meta"];
        };
        CitationUsagePageView: {
            items: components["schemas"]["CitationUsageView"][];
            next_cursor?: string;
            /** Format: int32 */
            limit: number;
            /** Format: int64 */
            total: number;
        };
        ApiEnvelopeListSourceView: {
            data: components["schemas"]["SourceView"][];
            meta: components["schemas"]["Meta"];
        };
        ApiEnvelopeSourceDetailView: {
            data: components["schemas"]["SourceDetailView"];
            meta: components["schemas"]["Meta"];
        };
        SourceDetailView: {
            source: components["schemas"]["SourceView"];
            documents: components["schemas"]["DocumentView"][];
            /** Format: int32 */
            published_unit_count: number;
            /** Format: int32 */
            embedding_unit_count: number;
            /** Format: int32 */
            citation_count: number;
            /** Format: int32 */
            retrieval_usage_count: number;
            current_index_version: string;
            embedding_provenance?: components["schemas"]["EmbeddingProvenanceView"];
        };
        ApiEnvelopeUnitPageView: {
            data: components["schemas"]["UnitPageView"];
            meta: components["schemas"]["Meta"];
        };
        UnitPageView: {
            items: components["schemas"]["UnitSummaryView"][];
            next_cursor?: string;
            /** Format: int32 */
            limit: number;
        };
        UnitSummaryView: {
            id: string;
            knowledge_source_id: string;
            document_id: string;
            topic?: string;
            title: string;
            expected_predicates: unknown;
            source_locator: unknown;
            source_version: string;
            content_hash: string;
            status: string;
            embedding_present: boolean;
            /** Format: date-time */
            created_at: string;
        };
        ApiEnvelopeListDocumentView: {
            data: components["schemas"]["DocumentView"][];
            meta: components["schemas"]["Meta"];
        };
        ApiEnvelopeListNextEvidenceView: {
            data: components["schemas"]["NextEvidenceView"][];
            meta: components["schemas"]["Meta"];
        };
        ApiEnvelopeKnowledgeContextView: {
            data: components["schemas"]["KnowledgeContextView"];
            meta: components["schemas"]["Meta"];
        };
        KnowledgeCitationView: {
            id: string;
            knowledge_unit_id: string;
            target_type: string;
            target_id: string;
            source_locator: unknown;
            source_version: string;
            content_hash: string;
            usage_reason: string;
            /** Format: date-time */
            created_at: string;
        };
        KnowledgeContextView: {
            investigation_run_id: string;
            retrieval_run_id: string;
            index_version: string;
            context_hash: string;
            query_plan: components["schemas"]["QueryPlanView"];
            citations: components["schemas"]["KnowledgeCitationView"][];
        };
        QueryIntentView: {
            type: string;
            query: string;
        };
        QueryPlanView: {
            domain_pack_key: string;
            planner_version: string;
            /** Format: int32 */
            keyword_top_k: number;
            /** Format: int32 */
            vector_top_k: number;
            /** Format: int32 */
            final_top_k: number;
            intents: components["schemas"]["QueryIntentView"][];
        };
        ApiEnvelopeRunDiffView: {
            data: components["schemas"]["RunDiffView"];
            meta: components["schemas"]["Meta"];
        };
        HypothesisChangeView: {
            code: string;
            title: string;
            /** Format: int32 */
            before_score?: number;
            /** Format: int32 */
            after_score?: number;
            /** Format: int32 */
            score_delta?: number;
            /** Format: double */
            before_coverage?: number;
            /** Format: double */
            after_coverage?: number;
        };
        RunDiffView: {
            base_run_id: string;
            current_run_id: string;
            /** Format: int32 */
            event_version_delta: number;
            evidence_snapshot_changed: boolean;
            knowledge_index_changed: boolean;
            hypothesis_changes: components["schemas"]["HypothesisChangeView"][];
            added_evidence_ids: string[];
            removed_evidence_ids: string[];
        };
        ApiEnvelopeEvidencePage: {
            data: components["schemas"]["EvidencePage"];
            meta: components["schemas"]["Meta"];
        };
        EvidencePage: {
            items: components["schemas"]["EvidenceSummary"][];
            next_cursor?: string;
            /** Format: int32 */
            limit: number;
            /** Format: int64 */
            total: number;
        };
        ApiEnvelopeEventPage: {
            data: components["schemas"]["EventPage"];
            meta: components["schemas"]["Meta"];
        };
        EventPage: {
            items: components["schemas"]["EventSummary"][];
            next_cursor?: string;
            /** Format: int32 */
            limit: number;
            /** Format: int64 */
            total: number;
        };
        EventSummary: {
            id: string;
            reference_code: string;
            event_type: string;
            title: string;
            description?: string;
            status: string;
            domain_pack_key: string;
            location_name?: string;
            /** Format: date-time */
            occurred_start?: string;
            /** Format: date-time */
            occurred_end?: string;
            /** Format: int64 */
            version: number;
            /** Format: int32 */
            evidence_count: number;
            /** Format: int32 */
            latest_score?: number;
            /** Format: double */
            latest_coverage?: number;
            top_hypothesis?: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApiEnvelopeEventDetail: {
            data: components["schemas"]["EventDetail"];
            meta: components["schemas"]["Meta"];
        };
        EventDetail: {
            id: string;
            reference_code: string;
            event_type: string;
            title: string;
            description?: string;
            status: string;
            domain_pack_key: string;
            location_name?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            /** Format: date-time */
            occurred_start?: string;
            /** Format: date-time */
            occurred_end?: string;
            /** Format: int64 */
            version: number;
            event_ir: unknown;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApiEnvelopeEventView: {
            data: components["schemas"]["EventView"];
            meta: components["schemas"]["Meta"];
        };
        EventView: {
            event: components["schemas"]["EventDetail"];
            evidence: components["schemas"]["EvidenceProjection"][];
            latest_investigation?: components["schemas"]["LatestInvestigationView"];
            stale: boolean;
            unresolved_gaps: components["schemas"]["GapSummary"][];
        };
        EvidenceProjection: {
            id: string;
            type: string;
            source: string;
            status: string;
            original_name?: string;
            content_type?: string;
            /** Format: int32 */
            generation: number;
            /** Format: double */
            reliability: number;
            /** Format: date-time */
            created_at: string;
        };
        GapSummary: {
            id: string;
            title: string;
            estimated_impact: string;
            acquisition_cost: string;
            /** Format: double */
            priority_score: number;
            status: string;
        };
        LatestInvestigationView: {
            id: string;
            /** Format: int32 */
            sequence_no: number;
            status: string;
            /** Format: int64 */
            event_version: number;
            /** Format: int32 */
            evidence_snapshot_schema_version: number;
            evidence_snapshot_hash: string;
            knowledge_index_version: string;
            result?: components["schemas"]["InvestigationResultView"];
            /** Format: date-time */
            completed_at?: string;
        };
        ApiEnvelopeInvestigationPage: {
            data: components["schemas"]["InvestigationPage"];
            meta: components["schemas"]["Meta"];
        };
        InvestigationPage: {
            items: components["schemas"]["InvestigationRunView"][];
            next_cursor?: string;
            /** Format: int32 */
            limit: number;
            /** Format: int64 */
            total: number;
        };
        ApiEnvelopeGraphView: {
            data: components["schemas"]["GraphView"];
            meta: components["schemas"]["Meta"];
        };
        GraphEdge: {
            id: string;
            source: string;
            target: string;
            type: string;
            /** Format: double */
            contribution?: number;
            score_affecting: boolean;
            explanation?: string;
            metadata: unknown;
        };
        GraphNode: {
            id: string;
            entity_id: string;
            type: string;
            label: string;
            subtitle?: string;
            status?: string;
            /** Format: double */
            score?: number;
            /** Format: double */
            coverage?: number;
            metadata: unknown;
        };
        GraphView: {
            event_id: string;
            investigation_run_id: string;
            stale: boolean;
            warnings: string[];
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
        };
        ApiEnvelopeAuditPage: {
            data: components["schemas"]["AuditPage"];
            meta: components["schemas"]["Meta"];
        };
        AuditEntry: {
            id: string;
            actor: unknown;
            action: string;
            resource: unknown;
            before_state: unknown;
            after_state: unknown;
            request_id?: string;
            /** Format: date-time */
            occurred_at: string;
        };
        AuditPage: {
            items: components["schemas"]["AuditEntry"][];
            next_cursor?: string;
            /** Format: int32 */
            limit: number;
        };
        StreamingResponseBody: Record<string, never>;
        ApiEnvelopeListDomainPackSummary: {
            data: components["schemas"]["DomainPackSummary"][];
            meta: components["schemas"]["Meta"];
        };
        DomainPackSummary: {
            key: string;
            version: string;
            name: string;
            description: string;
            status: string;
            fixture_only: boolean;
            production_allowed: boolean;
            compatible_eventir: string;
            /** Format: int32 */
            hypothesis_count: number;
            /** Format: int32 */
            rule_count: number;
            /** Format: int32 */
            document_count: number;
            /** Format: int32 */
            unit_count: number;
            knowledge_source_id?: string;
            knowledge_index_version?: string;
            presentation_locale: string;
            fingerprint: string;
            event_types: string[];
            vector_policy: string;
            observation_bundle: unknown;
            supported_target_versions?: components["schemas"]["TargetVersionView"];
            source_profiles: unknown;
            licenses: unknown;
            ready: boolean;
            readiness_reasons: string[];
        };
        TargetVersionView: {
            scheme: string;
            minimum?: string;
            maximum_exclusive?: string;
        };
        ApiEnvelopeDomainPackDetail: {
            data: components["schemas"]["DomainPackDetail"];
            meta: components["schemas"]["Meta"];
        };
        DomainPackDetail: {
            summary: components["schemas"]["DomainPackSummary"];
            manifest: unknown;
            event_definitions: components["schemas"]["EventTypeView"][];
            vocabulary: unknown;
            presentation: unknown;
            hypotheses: unknown;
            rules: unknown;
            next_evidence: unknown;
            retrieval_config: unknown;
            knowledge_metadata: unknown;
            warnings: string[];
        };
        EventPresentationView: {
            label: string;
            subject_label: string;
            fields: components["schemas"]["FieldPresentationView"][];
        };
        EventRequirementsView: {
            time_range: string;
        };
        EventTypeView: {
            domain_pack: string;
            event_type: string;
            subject_type: string;
            identity_fields: string[];
            label_template: string;
            attributes_schema: unknown;
            event_requirements: components["schemas"]["EventRequirementsView"];
            evidence_inputs: components["schemas"]["EvidenceInputView"][];
            target_versions?: components["schemas"]["TargetVersionView"];
            presentation: components["schemas"]["EventPresentationView"];
        };
        EvidenceInputView: {
            type: string;
            enabled: boolean;
            source_profile?: string;
            /** Format: double */
            source_reliability?: number;
            predicate?: string;
            verification_status?: string;
            requires_human_confirmation: boolean;
            content_types: string[];
            label?: string;
            help?: string;
            collector_command?: string;
        };
        FieldOptionView: {
            value: string;
            label: string;
        };
        FieldPresentationView: {
            name: string;
            label: string;
            control: string;
            placeholder?: string;
            required: boolean;
            options: components["schemas"]["FieldOptionView"][];
        };
        ApiEnvelopeEventTypeView: {
            data: components["schemas"]["EventTypeView"];
            meta: components["schemas"]["Meta"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    debug: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeRetrievalRunView"];
                };
            };
        };
    };
    reprocess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeEvidenceDetail"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                query?: string;
                status?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeEventPage"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeObject"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeInvestigationPage"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeInvestigationRunView"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeEvidenceDetail"];
                };
            };
        };
    };
    createText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextEvidenceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeEvidenceDetail"];
                };
            };
        };
    };
    importBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationBundleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeObservationBundleImportView"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationVerificationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeObservationView"];
                };
            };
        };
    };
    runtime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeRuntimeView"];
                };
            };
        };
    };
    run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeRetrievalRunView"];
                };
            };
        };
    };
    unit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeUnitDetailView"];
                };
            };
        };
    };
    retrievalUsages: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeRetrievalUsagePageView"];
                };
            };
        };
    };
    citationUsages: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeCitationUsagePageView"];
                };
            };
        };
    };
    sources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeListSourceView"];
                };
            };
        };
    };
    source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeSourceDetailView"];
                };
            };
        };
    };
    units: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeUnitPageView"];
                };
            };
        };
    };
    documents: {
        parameters: {
            query?: {
                source_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeListDocumentView"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeInvestigationRunView"];
                };
            };
        };
    };
    nextEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeListNextEvidenceView"];
                };
            };
        };
    };
    knowledgeContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeKnowledgeContextView"];
                };
            };
        };
    };
    diff: {
        parameters: {
            query?: {
                against?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeRunDiffView"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                event_id?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeEvidencePage"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeEvidenceDetail"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeEventDetail"];
                };
            };
        };
    };
    view: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeEventView"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query: {
                investigation_id: string;
            };
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeGraphView"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                actor_id?: string;
                action?: string;
                run_id?: string;
            };
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeAuditPage"];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: {
                actor_id?: string;
                action?: string;
                run_id?: string;
            };
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StreamingResponseBody"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeListDomainPackSummary"];
                };
            };
        };
    };
    get_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeDomainPackDetail"];
                };
            };
        };
    };
    getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
                version: string;
                eventType: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeEventTypeView"];
                };
            };
        };
    };
}
